name: coco-val2017
images_root: data/coco/val2017/images
derivatives_root: data/coco/val2017/derivatives
annotations_file: data/coco/annotations/instances_val2017.json
splits:
  train_fraction: 0.8
  seed: 2025
transforms:
  jpeg:
    quality: [95, 85, 75, 60]
  gaussian_noise:
    sigma: [2, 5, 10]
  rotate:
    degrees: [-8, -4, 4, 8]
  scale:
    factors: [0.9, 1.1]
  crop:
    fraction: [0.05, 0.10]
  color_jitter:
    brightness: 0.1
    contrast: 0.1
    saturation: 0.1
